// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY BELGIAN ROBOTS.

// WARNING: This file has automatically been generated on Mon, 29 Jun 2020 19:56:25 MDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Provides Go bindings for OpenAL Soft
*/
package openal_go
