// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY BELGIAN ROBOTS.

// WARNING: This file has automatically been generated on Wed, 1 Jul 2020 12:00:25 MDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package al

/*
#cgo pkg-config: openal
#include "AL/al.h"
#include "AL/alc.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// ALboolean type as declared in AL/al.h:38
type ALboolean byte

// ALchar type as declared in AL/al.h:41
type ALchar byte

// ALbyte type as declared in AL/al.h:44
type ALbyte int8

// ALubyte type as declared in AL/al.h:47
type ALubyte byte

// ALshort type as declared in AL/al.h:50
type ALshort int16

// ALushort type as declared in AL/al.h:53
type ALushort uint16

// ALint type as declared in AL/al.h:56
type ALint int32

// ALuint type as declared in AL/al.h:59
type ALuint uint32

// ALsizei type as declared in AL/al.h:62
type ALsizei int32

// ALenum type as declared in AL/al.h:65
type ALenum int32

// ALfloat type as declared in AL/al.h:68
type ALfloat float32

// ALdouble type as declared in AL/al.h:71
type ALdouble float64

// ALvoid type as declared in AL/al.h:74
type ALvoid [0]byte

// LPALENABLE type as declared in AL/al.h:578
type LPALENABLE func(capability ALenum)

// LPALDISABLE type as declared in AL/al.h:579
type LPALDISABLE func(capability ALenum)

// LPALISENABLED type as declared in AL/al.h:580
type LPALISENABLED func(capability ALenum) ALboolean

// LPALGETSTRING type as declared in AL/al.h:581
type LPALGETSTRING func(param ALenum) *ALchar

// LPALGETBOOLEANV type as declared in AL/al.h:582
type LPALGETBOOLEANV func(param ALenum, values []ALboolean)

// LPALGETINTEGERV type as declared in AL/al.h:583
type LPALGETINTEGERV func(param ALenum, values []ALint)

// LPALGETFLOATV type as declared in AL/al.h:584
type LPALGETFLOATV func(param ALenum, values []ALfloat)

// LPALGETDOUBLEV type as declared in AL/al.h:585
type LPALGETDOUBLEV func(param ALenum, values []ALdouble)

// LPALGETBOOLEAN type as declared in AL/al.h:586
type LPALGETBOOLEAN func(param ALenum) ALboolean

// LPALGETINTEGER type as declared in AL/al.h:587
type LPALGETINTEGER func(param ALenum) ALint

// LPALGETFLOAT type as declared in AL/al.h:588
type LPALGETFLOAT func(param ALenum) ALfloat

// LPALGETDOUBLE type as declared in AL/al.h:589
type LPALGETDOUBLE func(param ALenum) ALdouble

// LPALGETERROR type as declared in AL/al.h:590
type LPALGETERROR func() ALenum

// LPALISEXTENSIONPRESENT type as declared in AL/al.h:591
type LPALISEXTENSIONPRESENT func(extname []ALchar) ALboolean

// LPALGETPROCADDRESS type as declared in AL/al.h:592
type LPALGETPROCADDRESS func(fname []ALchar) unsafe.Pointer

// LPALGETENUMVALUE type as declared in AL/al.h:593
type LPALGETENUMVALUE func(ename []ALchar) ALenum

// LPALLISTENERF type as declared in AL/al.h:594
type LPALLISTENERF func(param ALenum, value ALfloat)

// LPALLISTENER3F type as declared in AL/al.h:595
type LPALLISTENER3F func(param ALenum, value1 ALfloat, value2 ALfloat, value3 ALfloat)

// LPALLISTENERFV type as declared in AL/al.h:596
type LPALLISTENERFV func(param ALenum, values []ALfloat)

// LPALLISTENERI type as declared in AL/al.h:597
type LPALLISTENERI func(param ALenum, value ALint)

// LPALLISTENER3I type as declared in AL/al.h:598
type LPALLISTENER3I func(param ALenum, value1 ALint, value2 ALint, value3 ALint)

// LPALLISTENERIV type as declared in AL/al.h:599
type LPALLISTENERIV func(param ALenum, values []ALint)

// LPALGETLISTENERF type as declared in AL/al.h:600
type LPALGETLISTENERF func(param ALenum, value []ALfloat)

// LPALGETLISTENER3F type as declared in AL/al.h:601
type LPALGETLISTENER3F func(param ALenum, value1 []ALfloat, value2 []ALfloat, value3 []ALfloat)

// LPALGETLISTENERFV type as declared in AL/al.h:602
type LPALGETLISTENERFV func(param ALenum, values []ALfloat)

// LPALGETLISTENERI type as declared in AL/al.h:603
type LPALGETLISTENERI func(param ALenum, value []ALint)

// LPALGETLISTENER3I type as declared in AL/al.h:604
type LPALGETLISTENER3I func(param ALenum, value1 []ALint, value2 []ALint, value3 []ALint)

// LPALGETLISTENERIV type as declared in AL/al.h:605
type LPALGETLISTENERIV func(param ALenum, values []ALint)

// LPALGENSOURCES type as declared in AL/al.h:606
type LPALGENSOURCES func(n ALsizei, sources []ALuint)

// LPALDELETESOURCES type as declared in AL/al.h:607
type LPALDELETESOURCES func(n ALsizei, sources []ALuint)

// LPALISSOURCE type as declared in AL/al.h:608
type LPALISSOURCE func(source ALuint) ALboolean

// LPALSOURCEF type as declared in AL/al.h:609
type LPALSOURCEF func(source ALuint, param ALenum, value ALfloat)

// LPALSOURCE3F type as declared in AL/al.h:610
type LPALSOURCE3F func(source ALuint, param ALenum, value1 ALfloat, value2 ALfloat, value3 ALfloat)

// LPALSOURCEFV type as declared in AL/al.h:611
type LPALSOURCEFV func(source ALuint, param ALenum, values []ALfloat)

// LPALSOURCEI type as declared in AL/al.h:612
type LPALSOURCEI func(source ALuint, param ALenum, value ALint)

// LPALSOURCE3I type as declared in AL/al.h:613
type LPALSOURCE3I func(source ALuint, param ALenum, value1 ALint, value2 ALint, value3 ALint)

// LPALSOURCEIV type as declared in AL/al.h:614
type LPALSOURCEIV func(source ALuint, param ALenum, values []ALint)

// LPALGETSOURCEF type as declared in AL/al.h:615
type LPALGETSOURCEF func(source ALuint, param ALenum, value []ALfloat)

// LPALGETSOURCE3F type as declared in AL/al.h:616
type LPALGETSOURCE3F func(source ALuint, param ALenum, value1 []ALfloat, value2 []ALfloat, value3 []ALfloat)

// LPALGETSOURCEFV type as declared in AL/al.h:617
type LPALGETSOURCEFV func(source ALuint, param ALenum, values []ALfloat)

// LPALGETSOURCEI type as declared in AL/al.h:618
type LPALGETSOURCEI func(source ALuint, param ALenum, value []ALint)

// LPALGETSOURCE3I type as declared in AL/al.h:619
type LPALGETSOURCE3I func(source ALuint, param ALenum, value1 []ALint, value2 []ALint, value3 []ALint)

// LPALGETSOURCEIV type as declared in AL/al.h:620
type LPALGETSOURCEIV func(source ALuint, param ALenum, values []ALint)

// LPALSOURCEPLAYV type as declared in AL/al.h:621
type LPALSOURCEPLAYV func(n ALsizei, sources []ALuint)

// LPALSOURCESTOPV type as declared in AL/al.h:622
type LPALSOURCESTOPV func(n ALsizei, sources []ALuint)

// LPALSOURCEREWINDV type as declared in AL/al.h:623
type LPALSOURCEREWINDV func(n ALsizei, sources []ALuint)

// LPALSOURCEPAUSEV type as declared in AL/al.h:624
type LPALSOURCEPAUSEV func(n ALsizei, sources []ALuint)

// LPALSOURCEPLAY type as declared in AL/al.h:625
type LPALSOURCEPLAY func(source ALuint)

// LPALSOURCESTOP type as declared in AL/al.h:626
type LPALSOURCESTOP func(source ALuint)

// LPALSOURCEREWIND type as declared in AL/al.h:627
type LPALSOURCEREWIND func(source ALuint)

// LPALSOURCEPAUSE type as declared in AL/al.h:628
type LPALSOURCEPAUSE func(source ALuint)

// LPALSOURCEQUEUEBUFFERS type as declared in AL/al.h:629
type LPALSOURCEQUEUEBUFFERS func(source ALuint, nb ALsizei, buffers []ALuint)

// LPALSOURCEUNQUEUEBUFFERS type as declared in AL/al.h:630
type LPALSOURCEUNQUEUEBUFFERS func(source ALuint, nb ALsizei, buffers []ALuint)

// LPALGENBUFFERS type as declared in AL/al.h:631
type LPALGENBUFFERS func(n ALsizei, buffers []ALuint)

// LPALDELETEBUFFERS type as declared in AL/al.h:632
type LPALDELETEBUFFERS func(n ALsizei, buffers []ALuint)

// LPALISBUFFER type as declared in AL/al.h:633
type LPALISBUFFER func(buffer ALuint) ALboolean

// LPALBUFFERDATA type as declared in AL/al.h:634
type LPALBUFFERDATA func(buffer ALuint, format ALenum, data *ALvoid, size ALsizei, freq ALsizei)

// LPALBUFFERF type as declared in AL/al.h:635
type LPALBUFFERF func(buffer ALuint, param ALenum, value ALfloat)

// LPALBUFFER3F type as declared in AL/al.h:636
type LPALBUFFER3F func(buffer ALuint, param ALenum, value1 ALfloat, value2 ALfloat, value3 ALfloat)

// LPALBUFFERFV type as declared in AL/al.h:637
type LPALBUFFERFV func(buffer ALuint, param ALenum, values []ALfloat)

// LPALBUFFERI type as declared in AL/al.h:638
type LPALBUFFERI func(buffer ALuint, param ALenum, value ALint)

// LPALBUFFER3I type as declared in AL/al.h:639
type LPALBUFFER3I func(buffer ALuint, param ALenum, value1 ALint, value2 ALint, value3 ALint)

// LPALBUFFERIV type as declared in AL/al.h:640
type LPALBUFFERIV func(buffer ALuint, param ALenum, values []ALint)

// LPALGETBUFFERF type as declared in AL/al.h:641
type LPALGETBUFFERF func(buffer ALuint, param ALenum, value []ALfloat)

// LPALGETBUFFER3F type as declared in AL/al.h:642
type LPALGETBUFFER3F func(buffer ALuint, param ALenum, value1 []ALfloat, value2 []ALfloat, value3 []ALfloat)

// LPALGETBUFFERFV type as declared in AL/al.h:643
type LPALGETBUFFERFV func(buffer ALuint, param ALenum, values []ALfloat)

// LPALGETBUFFERI type as declared in AL/al.h:644
type LPALGETBUFFERI func(buffer ALuint, param ALenum, value []ALint)

// LPALGETBUFFER3I type as declared in AL/al.h:645
type LPALGETBUFFER3I func(buffer ALuint, param ALenum, value1 []ALint, value2 []ALint, value3 []ALint)

// LPALGETBUFFERIV type as declared in AL/al.h:646
type LPALGETBUFFERIV func(buffer ALuint, param ALenum, values []ALint)

// LPALDOPPLERFACTOR type as declared in AL/al.h:647
type LPALDOPPLERFACTOR func(value ALfloat)

// LPALDOPPLERVELOCITY type as declared in AL/al.h:648
type LPALDOPPLERVELOCITY func(value ALfloat)

// LPALSPEEDOFSOUND type as declared in AL/al.h:649
type LPALSPEEDOFSOUND func(value ALfloat)

// LPALDISTANCEMODEL type as declared in AL/al.h:650
type LPALDISTANCEMODEL func(distanceModel ALenum)

// ALCdevice as declared in AL/alc.h:34
type ALCdevice C.ALCdevice

// ALCcontext as declared in AL/alc.h:36
type ALCcontext C.ALCcontext

// ALCboolean type as declared in AL/alc.h:39
type ALCboolean byte

// ALCchar type as declared in AL/alc.h:42
type ALCchar byte

// ALCbyte type as declared in AL/alc.h:45
type ALCbyte int8

// ALCubyte type as declared in AL/alc.h:48
type ALCubyte byte

// ALCshort type as declared in AL/alc.h:51
type ALCshort int16

// ALCushort type as declared in AL/alc.h:54
type ALCushort uint16

// ALCint type as declared in AL/alc.h:57
type ALCint int32

// ALCuint type as declared in AL/alc.h:60
type ALCuint uint32

// ALCsizei type as declared in AL/alc.h:63
type ALCsizei int32

// ALCenum type as declared in AL/alc.h:66
type ALCenum int32

// ALCfloat type as declared in AL/alc.h:69
type ALCfloat float32

// ALCdouble type as declared in AL/alc.h:72
type ALCdouble float64

// ALCvoid type as declared in AL/alc.h:75
type ALCvoid [0]byte

// LPALCCREATECONTEXT type as declared in AL/alc.h:212
type LPALCCREATECONTEXT func(device []ALCdevice, attrlist []ALCint) *ALCcontext

// LPALCMAKECONTEXTCURRENT type as declared in AL/alc.h:213
type LPALCMAKECONTEXTCURRENT func(context []ALCcontext) ALCboolean

// LPALCPROCESSCONTEXT type as declared in AL/alc.h:214
type LPALCPROCESSCONTEXT func(context []ALCcontext)

// LPALCSUSPENDCONTEXT type as declared in AL/alc.h:215
type LPALCSUSPENDCONTEXT func(context []ALCcontext)

// LPALCDESTROYCONTEXT type as declared in AL/alc.h:216
type LPALCDESTROYCONTEXT func(context []ALCcontext)

// LPALCGETCURRENTCONTEXT type as declared in AL/alc.h:217
type LPALCGETCURRENTCONTEXT func() *ALCcontext

// LPALCGETCONTEXTSDEVICE type as declared in AL/alc.h:218
type LPALCGETCONTEXTSDEVICE func(context []ALCcontext) *ALCdevice

// LPALCOPENDEVICE type as declared in AL/alc.h:219
type LPALCOPENDEVICE func(devicename []ALCchar) *ALCdevice

// LPALCCLOSEDEVICE type as declared in AL/alc.h:220
type LPALCCLOSEDEVICE func(device []ALCdevice) ALCboolean

// LPALCGETERROR type as declared in AL/alc.h:221
type LPALCGETERROR func(device []ALCdevice) ALCenum

// LPALCISEXTENSIONPRESENT type as declared in AL/alc.h:222
type LPALCISEXTENSIONPRESENT func(device []ALCdevice, extname []ALCchar) ALCboolean

// LPALCGETPROCADDRESS type as declared in AL/alc.h:223
type LPALCGETPROCADDRESS func(device []ALCdevice, funcname []ALCchar) unsafe.Pointer

// LPALCGETENUMVALUE type as declared in AL/alc.h:224
type LPALCGETENUMVALUE func(device []ALCdevice, enumname []ALCchar) ALCenum

// LPALCGETSTRING type as declared in AL/alc.h:225
type LPALCGETSTRING func(device []ALCdevice, param ALCenum) *ALCchar

// LPALCGETINTEGERV type as declared in AL/alc.h:226
type LPALCGETINTEGERV func(device []ALCdevice, param ALCenum, size ALCsizei, values []ALCint)

// LPALCCAPTUREOPENDEVICE type as declared in AL/alc.h:227
type LPALCCAPTUREOPENDEVICE func(devicename []ALCchar, frequency ALCuint, format ALCenum, buffersize ALCsizei) *ALCdevice

// LPALCCAPTURECLOSEDEVICE type as declared in AL/alc.h:228
type LPALCCAPTURECLOSEDEVICE func(device []ALCdevice) ALCboolean

// LPALCCAPTURESTART type as declared in AL/alc.h:229
type LPALCCAPTURESTART func(device []ALCdevice)

// LPALCCAPTURESTOP type as declared in AL/alc.h:230
type LPALCCAPTURESTOP func(device []ALCdevice)

// LPALCCAPTURESAMPLES type as declared in AL/alc.h:231
type LPALCCAPTURESAMPLES func(device []ALCdevice, buffer *ALCvoid, samples ALCsizei)
