// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 07 Jul 2020 19:05:22 MDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "stb_vorbis.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

