// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 07 Jul 2020 19:05:22 MDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package vorbis

/*
#include "stb_vorbis.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// stbvorbiserror as declared in vorbis/stb_vorbis.c:363
type stbvorbiserror int32

// stbvorbiserror enumeration from vorbis/stb_vorbis.c:363
const ()
