// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 07 Jul 2020 19:05:22 MDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package vorbis

/*
#include "stb_vorbis.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// stb_vorbis_alloc as declared in vorbis/stb_vorbis.c:117
type stb_vorbis_alloc struct {
	alloc_buffer                 []byte
	alloc_buffer_length_in_bytes int32
	ref10434850                  *C.stb_vorbis_alloc
	allocs10434850               interface{}
}

// stb_vorbis as declared in vorbis/stb_vorbis.c:122
type stb_vorbis C.stb_vorbis

// stb_vorbis_info as declared in vorbis/stb_vorbis.c:134
type stb_vorbis_info struct {
	sample_rate                uint32
	channels                   int32
	setup_memory_required      uint32
	setup_temp_memory_required uint32
	temp_memory_required       uint32
	max_frame_size             int32
	refaa876ed4                *C.stb_vorbis_info
	allocsaa876ed4             interface{}
}

// stb_vorbis_comment as declared in vorbis/stb_vorbis.c:142
type stb_vorbis_comment struct {
	vendor              []byte
	comment_list_length int32
	comment_list        [][]byte
	refad9c9b48         *C.stb_vorbis_comment
	allocsad9c9b48      interface{}
}

// file as declared in types/FILE.h:7
type file struct {
	_flags          int32
	_io_read_ptr    []byte
	_io_read_end    []byte
	_io_read_base   []byte
	_io_write_base  []byte
	_io_write_ptr   []byte
	_io_write_end   []byte
	_io_buf_base    []byte
	_io_buf_end     []byte
	_io_save_base   []byte
	_io_backup_base []byte
	_io_save_end    []byte
	_fileno         int32
	_flags2         int32
	_old_offset     int
	_cur_column     uint16
	_vtable_offset  int8
	_shortbuf       [1]byte
	_lock           unsafe.Pointer
	_offset         int
	_freeres_buf    unsafe.Pointer
	__pad5          uint
	_mode           int32
	_unused2        [20]byte
	refba0adba4     *C.FILE
	allocsba0adba4  interface{}
}
