// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY BELGIAN ROBOTS.

// WARNING: This file has automatically been generated on Mon, 29 Jun 2020 19:56:25 MDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void LPALENABLE_c158bd47(int capability) {
	lPALENABLEC158BD47(capability);
}

void LPALDISABLE_5476105f(int capability) {
	lPALDISABLE5476105F(capability);
}

char LPALISENABLED_dc30ce46(int capability) {
	return lPALISENABLEDDC30CE46(capability);
}

char* LPALGETSTRING_54e8aeb0(int param) {
	return lPALGETSTRING54E8AEB0(param);
}

void LPALGETBOOLEANV_96c6c0d(int param, char* values) {
	lPALGETBOOLEANV96C6C0D(param, values);
}

void LPALGETINTEGERV_dd07d6cc(int param, int* values) {
	lPALGETINTEGERVDD07D6CC(param, values);
}

void LPALGETFLOATV_219ee508(int param, float* values) {
	lPALGETFLOATV219EE508(param, values);
}

void LPALGETDOUBLEV_4c4fd8b(int param, double* values) {
	lPALGETDOUBLEV4C4FD8B(param, values);
}

char LPALGETBOOLEAN_d54a567c(int param) {
	return lPALGETBOOLEAND54A567C(param);
}

int LPALGETINTEGER_5c0751f(int param) {
	return lPALGETINTEGER5C0751F(param);
}

float LPALGETFLOAT_257bcd44(int param) {
	return lPALGETFLOAT257BCD44(param);
}

double LPALGETDOUBLE_10b1eef6(int param) {
	return lPALGETDOUBLE10B1EEF6(param);
}

int LPALGETERROR_b1032fa0() {
	return lPALGETERRORB1032FA0();
}

char LPALISEXTENSIONPRESENT_2de7d519(char* extname) {
	return lPALISEXTENSIONPRESENT2DE7D519(extname);
}

void* LPALGETPROCADDRESS_f3ca5dca(char* fname) {
	return lPALGETPROCADDRESSF3CA5DCA(fname);
}

int LPALGETENUMVALUE_5dc5dce(char* ename) {
	return lPALGETENUMVALUE5DC5DCE(ename);
}

void LPALLISTENERF_8695e9ae(int param, float value) {
	lPALLISTENERF8695E9AE(param, value);
}

void LPALLISTENER3F_2e1d9d9d(int param, float value1, float value2, float value3) {
	lPALLISTENER3F2E1D9D9D(param, value1, value2, value3);
}

void LPALLISTENERFV_61e2004a(int param, float* values) {
	lPALLISTENERFV61E2004A(param, values);
}

void LPALLISTENERI_162af43f(int param, int value) {
	lPALLISTENERI162AF43F(param, value);
}

void LPALLISTENER3I_bea2800c(int param, int value1, int value2, int value3) {
	lPALLISTENER3IBEA2800C(param, value1, value2, value3);
}

void LPALLISTENERIV_e67a1c85(int param, int* values) {
	lPALLISTENERIVE67A1C85(param, values);
}

void LPALGETLISTENERF_42098513(int param, float* value) {
	lPALGETLISTENERF42098513(param, value);
}

void LPALGETLISTENER3F_9b09cec0(int param, float* value1, float* value2, float* value3) {
	lPALGETLISTENER3F9B09CEC0(param, value1, value2, value3);
}

void LPALGETLISTENERFV_d4f65317(int param, float* values) {
	lPALGETLISTENERFVD4F65317(param, values);
}

void LPALGETLISTENERI_d2b69882(int param, int* value) {
	lPALGETLISTENERID2B69882(param, value);
}

void LPALGETLISTENER3I_bb6d351(int param, int* value1, int* value2, int* value3) {
	lPALGETLISTENER3IBB6D351(param, value1, value2, value3);
}

void LPALGETLISTENERIV_536e4fd8(int param, int* values) {
	lPALGETLISTENERIV536E4FD8(param, values);
}

void LPALGENSOURCES_60e99605(int n, unsigned int* sources) {
	lPALGENSOURCES60E99605(n, sources);
}

void LPALDELETESOURCES_9e261641(int n, unsigned int* sources) {
	lPALDELETESOURCES9E261641(n, sources);
}

char LPALISSOURCE_45834e0d(unsigned int source) {
	return lPALISSOURCE45834E0D(source);
}

void LPALSOURCEF_a4b3dc17(unsigned int source, int param, float value) {
	lPALSOURCEFA4B3DC17(source, param, value);
}

void LPALSOURCE3F_9c82b080(unsigned int source, int param, float value1, float value2, float value3) {
	lPALSOURCE3F9C82B080(source, param, value1, value2, value3);
}

void LPALSOURCEFV_d37d2d57(unsigned int source, int param, float* values) {
	lPALSOURCEFVD37D2D57(source, param, values);
}

void LPALSOURCEI_340cc186(unsigned int source, int param, int value) {
	lPALSOURCEI340CC186(source, param, value);
}

void LPALSOURCE3I_c3dad11(unsigned int source, int param, int value1, int value2, int value3) {
	lPALSOURCE3IC3DAD11(source, param, value1, value2, value3);
}

void LPALSOURCEIV_54e53198(unsigned int source, int param, int* values) {
	lPALSOURCEIV54E53198(source, param, values);
}

void LPALGETSOURCEF_e04f5f0d(unsigned int source, int param, float* value) {
	lPALGETSOURCEFE04F5F0D(source, param, value);
}

void LPALGETSOURCE3F_61a4b579(unsigned int source, int param, float* value1, float* value2, float* value3) {
	lPALGETSOURCE3F61A4B579(source, param, value1, value2, value3);
}

void LPALGETSOURCEFV_2e5b28ae(unsigned int source, int param, float* values) {
	lPALGETSOURCEFV2E5B28AE(source, param, values);
}

void LPALGETSOURCEI_70f0429c(unsigned int source, int param, int* value) {
	lPALGETSOURCEI70F0429C(source, param, value);
}

void LPALGETSOURCE3I_f11ba8e8(unsigned int source, int param, int* value1, int* value2, int* value3) {
	lPALGETSOURCE3IF11BA8E8(source, param, value1, value2, value3);
}

void LPALGETSOURCEIV_a9c33461(unsigned int source, int param, int* values) {
	lPALGETSOURCEIVA9C33461(source, param, values);
}

void LPALSOURCEPLAYV_d0019668(int n, unsigned int* sources) {
	lPALSOURCEPLAYVD0019668(n, sources);
}

void LPALSOURCESTOPV_d950058b(int n, unsigned int* sources) {
	lPALSOURCESTOPVD950058B(n, sources);
}

void LPALSOURCEREWINDV_fe90ec74(int n, unsigned int* sources) {
	lPALSOURCEREWINDVFE90EC74(n, sources);
}

void LPALSOURCEPAUSEV_5820338d(int n, unsigned int* sources) {
	lPALSOURCEPAUSEV5820338D(n, sources);
}

void LPALSOURCEPLAY_6eeaef95(unsigned int source) {
	lPALSOURCEPLAY6EEAEF95(source);
}

void LPALSOURCESTOP_89352799(unsigned int source) {
	lPALSOURCESTOP89352799(source);
}

void LPALSOURCEREWIND_4b9d72e8(unsigned int source) {
	lPALSOURCEREWIND4B9D72E8(source);
}

void LPALSOURCEPAUSE_4715ec4d(unsigned int source) {
	lPALSOURCEPAUSE4715EC4D(source);
}

void LPALSOURCEQUEUEBUFFERS_4c6e4ca3(unsigned int source, int nb, unsigned int* buffers) {
	lPALSOURCEQUEUEBUFFERS4C6E4CA3(source, nb, buffers);
}

void LPALSOURCEUNQUEUEBUFFERS_c16dec16(unsigned int source, int nb, unsigned int* buffers) {
	lPALSOURCEUNQUEUEBUFFERSC16DEC16(source, nb, buffers);
}

void LPALGENBUFFERS_fa38f53c(int n, unsigned int* buffers) {
	lPALGENBUFFERSFA38F53C(n, buffers);
}

void LPALDELETEBUFFERS_4f77578(int n, unsigned int* buffers) {
	lPALDELETEBUFFERS4F77578(n, buffers);
}

char LPALISBUFFER_2b53c18c(unsigned int buffer) {
	return lPALISBUFFER2B53C18C(buffer);
}

void LPALBUFFERDATA_92ec6ef(unsigned int buffer, int format, void* data, int size, int freq) {
	// lPALBUFFERDATA92EC6EF(buffer, format, data, size, freq);
}

void LPALBUFFERF_3e62bf2e(unsigned int buffer, int param, float value) {
	lPALBUFFERF3E62BF2E(buffer, param, value);
}

void LPALBUFFER3F_c31de9eb(unsigned int buffer, int param, float value1, float value2, float value3) {
	lPALBUFFER3FC31DE9EB(buffer, param, value1, value2, value3);
}

void LPALBUFFERFV_8ce2743c(unsigned int buffer, int param, float* values) {
	lPALBUFFERFV8CE2743C(buffer, param, values);
}

void LPALBUFFERI_aedda2bf(unsigned int buffer, int param, int value) {
	lPALBUFFERIAEDDA2BF(buffer, param, value);
}

void LPALBUFFER3I_53a2f47a(unsigned int buffer, int param, int value1, int value2, int value3) {
	lPALBUFFER3I53A2F47A(buffer, param, value1, value2, value3);
}

void LPALBUFFERIV_b7a68f3(unsigned int buffer, int param, int* values) {
	lPALBUFFERIVB7A68F3(buffer, param, values);
}

void LPALGETBUFFERF_7a9e3c34(unsigned int buffer, int param, float* value) {
	lPALGETBUFFERF7A9E3C34(buffer, param, value);
}

void LPALGETBUFFER3F_3e3bec12(unsigned int buffer, int param, float* value1, float* value2, float* value3) {
	lPALGETBUFFER3F3E3BEC12(buffer, param, value1, value2, value3);
}

void LPALGETBUFFERFV_71c471c5(unsigned int buffer, int param, float* values) {
	lPALGETBUFFERFV71C471C5(buffer, param, values);
}

void LPALGETBUFFERI_ea2121a5(unsigned int buffer, int param, int* value) {
	lPALGETBUFFERIEA2121A5(buffer, param, value);
}

void LPALGETBUFFER3I_ae84f183(unsigned int buffer, int param, int* value1, int* value2, int* value3) {
	lPALGETBUFFER3IAE84F183(buffer, param, value1, value2, value3);
}

void LPALGETBUFFERIV_f65c6d0a(unsigned int buffer, int param, int* values) {
	lPALGETBUFFERIVF65C6D0A(buffer, param, values);
}

void LPALDOPPLERFACTOR_6e5e34c4(float value) {
	lPALDOPPLERFACTOR6E5E34C4(value);
}

void LPALDOPPLERVELOCITY_37ac1909(float value) {
	lPALDOPPLERVELOCITY37AC1909(value);
}

void LPALSPEEDOFSOUND_c05fbd29(float value) {
	lPALSPEEDOFSOUNDC05FBD29(value);
}

void LPALDISTANCEMODEL_69926daa(int distanceModel) {
	lPALDISTANCEMODEL69926DAA(distanceModel);
}

ALCcontext* LPALCCREATECONTEXT_b16fc55a(ALCdevice* device, int* attrlist) {
	return lPALCCREATECONTEXTB16FC55A(device, attrlist);
}

char LPALCMAKECONTEXTCURRENT_c13d1dfc(ALCcontext* context) {
	return lPALCMAKECONTEXTCURRENTC13D1DFC(context);
}

void LPALCPROCESSCONTEXT_80cc7c79(ALCcontext* context) {
	lPALCPROCESSCONTEXT80CC7C79(context);
}

void LPALCSUSPENDCONTEXT_9429c059(ALCcontext* context) {
	lPALCSUSPENDCONTEXT9429C059(context);
}

void LPALCDESTROYCONTEXT_a63f2985(ALCcontext* context) {
	lPALCDESTROYCONTEXTA63F2985(context);
}

ALCcontext* LPALCGETCURRENTCONTEXT_9ef7ba4c() {
	return lPALCGETCURRENTCONTEXT9EF7BA4C();
}

ALCdevice* LPALCGETCONTEXTSDEVICE_348eacee(ALCcontext* context) {
	return lPALCGETCONTEXTSDEVICE348EACEE(context);
}

ALCdevice* LPALCOPENDEVICE_45b1d80f(char* devicename) {
	return lPALCOPENDEVICE45B1D80F(devicename);
}

char LPALCCLOSEDEVICE_188afbc4(ALCdevice* device) {
	return lPALCCLOSEDEVICE188AFBC4(device);
}

int LPALCGETERROR_aeb8780a(ALCdevice* device) {
	return lPALCGETERRORAEB8780A(device);
}

char LPALCISEXTENSIONPRESENT_9fa44568(ALCdevice* device, char* extname) {
	return lPALCISEXTENSIONPRESENT9FA44568(device, extname);
}

void* LPALCGETPROCADDRESS_1c77514f(ALCdevice* device, char* funcname) {
	return lPALCGETPROCADDRESS1C77514F(device, funcname);
}

int LPALCGETENUMVALUE_c4c0e61c(ALCdevice* device, char* enumname) {
	return lPALCGETENUMVALUEC4C0E61C(device, enumname);
}

char* LPALCGETSTRING_62f45f11(ALCdevice* device, int param) {
	return lPALCGETSTRING62F45F11(device, param);
}

void LPALCGETINTEGERV_a0a1aff2(ALCdevice* device, int param, int size, int* values) {
	lPALCGETINTEGERVA0A1AFF2(device, param, size, values);
}

ALCdevice* LPALCCAPTUREOPENDEVICE_e864b189(char* devicename, unsigned int frequency, int format, int buffersize) {
	return lPALCCAPTUREOPENDEVICEE864B189(devicename, frequency, format, buffersize);
}

char LPALCCAPTURECLOSEDEVICE_1cfc08b8(ALCdevice* device) {
	return lPALCCAPTURECLOSEDEVICE1CFC08B8(device);
}

void LPALCCAPTURESTART_4f64c48c(ALCdevice* device) {
	lPALCCAPTURESTART4F64C48C(device);
}

void LPALCCAPTURESTOP_c4d1e273(ALCdevice* device) {
	lPALCCAPTURESTOPC4D1E273(device);
}

void LPALCCAPTURESAMPLES_1b5d7311(ALCdevice* device, void* buffer, int samples) {
	// lPALCCAPTURESAMPLES1B5D7311(device, buffer, samples);
}

